language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
env:
  - DB=mysql
  # - DB=postgresql
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rake test
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: bundle install
before_script:
  - "mkdir -p test/dummy/tmp/cache/"
  - mysql -e 'create database kinney_test;'
  - psql -c 'create database kinney_test;' -U postgres
  - "RAILS_ENV=test bundle exec rake db:create db:schema:load"
services:
  - elasticsearch