language: ruby
rvm:
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script: "bundle exec rake test"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: bundle install
before_script:
  - "mkdir -p test/dummy/tmp/cache/"
  - mysql -e 'create database kinney_test;'
  - psql -c 'create database kinney_test;' -U postgres
  - "RAILS_ENV=test bundle exec rake db:create db:migrate"
services:
  - elasticsearch